language: node_js
node_js:
  - 4
sudo: false
after_success:
  - npm run-script test:coverage
  - bash <(curl -s https://codecov.io/bash)
notifications:
  webhooks:
    urls:
      - https://podbot.pod-point.com/travis
